---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-app1
  name: demo-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app1
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-app1
    spec:
      containers:
      - image: prachimittal2016/argocd-demo:9
        name: demo-app1
        ports:
        - containerPort: 8080
---