apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: demo-app1
    server: "https://kubernetes.default.svc"
  source:
    path: overlays/prod/manifests/demo-app1
    repoURL: "https://github.tools.sap/I569818/argocd.git"
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  project: default