apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: demo-app
    server: "https://kubernetes.default.svc"
  source:
    path: overlays/prod/manifests/demo-app
    repoURL: "https://github.com/PrachiMittal2016/argocd-install.git"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  project: default
