apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
type: Opaque
data:
  accounts.user3.password: JDJhJDEwJERRQ2ZqcjRZOEk1V0xPeXNaU2xkeHVuVHN2UnIxd3lQU1Q1VDhKRnJkdFROSkdsZEdmRXBh