apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
bases:
  - ../base/
resources:
  - repo-secrets.yaml
patchesStrategicMerge:
  - argocd-secret-override.yaml
configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - "accounts.user3=apiKey,login"
      - "accounts.user3.enabled=true"
    files:
      - repositories=configs/repositories.yaml
      - repository.credentials=configs/repository-credentials.yaml
  - name: argocd-rbac-cm
    behavior: merge
    files:
      - configs/policy.csv