apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- namespace.yaml
- ./Non-HA/v2.5.5/install.yaml

namespace: argocd

commonLabels:
  app.kubernetes.io/name: argocd
  app.kubernetes.io/part-of: argo
